### ISSUE TITLE
import_logs.py Format

### ISSUE THREAD

**Issue by nuxwin** [piwik/piwik-log-analytics#100]
Please, be sure to convert the import_logs.py to UNIX format before releasing, else, you cannot execute that script directly due to wrong format (DOS format).

For instance, right now, it is mandatory to do:

```
CustomLog "| /usr/bin/python /var/www/virtual/test.tld/piwik/htdocs/misc/log-analytics/import_logs.py
```

while when the script is in UNIX format, it is sufficent to do

```
CustomLog "|/var/www/virtual/test.tld/piwik/htdocs/misc/log-analytics/import_logs.py
```

Right now, I fix the problem by converting the script using the dos2unix command (dos2unix package under Debian).

Thanks.

**Comment by mattab** [comment]
Hi @nuxwin 
What is the problem when you run the script? (error message, etc.)

> For instance, right now, it is mandatory to do:

fyi: both lines are the same in your issue

**Comment by nuxwin** [comment]
@mattab

Edited. Il'l show you the error.log soon ;)

**Comment by nuxwin** [comment]
@mattab 

The error message is something like "no such file or directory". Basically, this is due to the fact that the file format is wrong. A file format problem can display ^M characters, or can prevent scripts from running correctly. You must ensure to store that file in unix format in github. You can fix that with a .gitattributes file.

**Comment by nuxwin** [comment]
@mattab To resume, you should probably apply https://github.com/piwik/piwik/commit/b3e8537b4ba8ed1182fc7b2e647ad768ea8a9260 to this repository too ;)

**Comment by mattab** [comment]
Hi @nuxwin - Pull request would be very welcome :-)
