### ISSUE TITLE
add multiple files or a folder

### ISSUE THREAD

**Issue by Henner** [piwik/piwik-log-analytics#104]
please add a snippet, how to import all my old log files (folder) or add a parameter --folder to the script (maybe including unzip)

**Comment by dbinoj** [comment]
:+1:  +1 this will be really useful. We have logs sent to a central storage in the format `<host>/<vhost>/<year>/<month>/<date>_<access/error>.log` and old logs are gzipped automatically. It would be great if this script can go to specified folder, get all files, gunzip/unzip compressed files and send it to piwik. Recursive option also will be nice to have :+1:

**Comment by mattab** [comment]
Yes you can specify *.log and it will import all log files in the folder. This should already work. i'll make it more clear in the docs

**Comment by dbinoj** [comment]
@mattab will this work under directories recursively? Does the command have a recursive flag? sorry for asking another question to a answered thread. But felt it would go well with the context of this question.
