### ISSUE TITLE
Menu Layout problem  - Piwik 2.15.0-b17 

### ISSUE THREAD

**Issue by XinfinityoO** [piwik/piwik-log-analytics#108]
Menu is not properly layed out and i can't find any option to change it

![menu](https://cloud.githubusercontent.com/assets/3344044/10418992/3745eb6a-70c6-11e5-9065-125e033a3c1c.JPG)

**Comment by mattab** [comment]
Hi @XinfinityoO 

I moved your issue to the correct tracker: https://github.com/piwik/piwik/issues/8965
