### ISSUE TITLE
Option to use stdin readline

### ISSUE THREAD

**Issue by falstaff84** [piwik/piwik-log-analytics#111]
When using import_logs.py with Apache 2.4's CustomLog pipe option on a Ubuntu 12.04, I noticed that visits trickle in a bit delayed (on my machine 33 entries were necessary until the first visit got recorded). What is also interesting when shutting down the webserver, the remaining log entries do get lost! The python buffer options (-u) did not help to solve this issue. It would be nice to have an option to use the unbuffered sys.stdin.readline() when using CustomLog.

```
   -u     Force stdin, stdout and stderr to  be  totally  unbuffered.   On
          systems  where  it matters, also put stdin, stdout and stderr in
          binary mode.  Note that there is internal  buffering  in  xread-
          lines(),  readlines()  and  file-object  iterators ("for line in
          sys.stdin") which is not influenced by  this  option.   To  work
          around  this, you will want to use "sys.stdin.readline()" inside
          a "while 1:" loop.
```

**Comment by antoninblanc** [comment]
The patch https://issues.piwik.org/3757 works for me.

**Comment by mattab** [comment]
Hi @antoninblanc it would be useful if you can create a pull request on this repository with the working patch, test it, and then we will be happy to merge it for everyone to enjoy :+1:

**Comment by mattab** [comment]
Hi @falstaff84 can you please confirm whether the patch in https://github.com/piwik/piwik-log-analytics/issues/118 fixes the issue for you too?

**Comment by mattab** [comment]
Assuming https://github.com/piwik/piwik-log-analytics/pull/118 fixed this issue. If not, please reopen @antoninblanc @falstaff84
