### ISSUE TITLE
replay tracking fails to split visits per visitor from enterprise invironments 

### ISSUE THREAD

**Issue by RMastop** [piwik/piwik-log-analytics#112]
I tried to replay a set of log files with Piwik tracking containing visitors from an enterprise environment.
While using the setting --replay-tracking it fails to separate the individual visitors from visits.
The result is set of visits with 500+ actions in it.

I would expect Piwik to split the visits per visitor, like it does when tracking via JavaScript, because I have set the option to do so in config.ini.php:
[Tracker]
trust_visitors_cookies = 1

**Comment by mattab** [comment]
Hi @RMastop 
could you paste here a small log file (eg. 3-5 lines) that let us reproduce the problem? ie. ideally the log file lines would be from several visitors, but when running the import they would incorrectly be tracked in the same visit. Once we can reproduce with such small log file it will be easier to solve it. thanks

**Comment by RMastop** [comment]
Hi @mattab,

I'm not able to send some at the moment.
I think the problem is that there are no cookies in the logfiles. If the rest of the settings of the users are the same, piwik has no way of detecting different users. 
If I would add the piwik cookies to the logfiles, how would I be able to use them in the importer? Is there a  setting where I could connect the cookie value to?

Thanks,
Richard.

**Comment by mattab** [comment]
> I think the problem is that there are no cookies in the logfiles.

Yes, this is the problem. When [trust_visitors_cookies](https://piwik.org/faq/how-to/faq_175/) is used then the log file needs to have cookies.
