### ISSUE TITLE
How to import Shoutcast log files into Piwik for analysis

### ISSUE THREAD

**Issue by entropywaves** [piwik/piwik-log-analytics#114]
Hi,
I'm trying to extract information from Shoutcast streaming server logs but unfortunately struggling to set it up properly. I've seen some examples to extract Icecast log files which is a bit likewise. But I can't get it to work with Shoutcast. Hopefully anybody can help me out with this one;-) I'm trying to extract client details of listeners from the radio station (e.g. IP, streaming client software, etcetera).
I've added two log files the server generates, don't know which of the two is most suitable for import. Both seem to generate similar information. But I think that sc_serv.txt is the most readable log.

So hopefully anybody has the perfect recipe to import data into Piwik:-)

[sc_serv.txt](https://github.com/piwik/piwik-log-analytics/files/55085/sc_serv.txt)
[sc_w3c.txt](https://github.com/piwik/piwik-log-analytics/files/55086/sc_w3c.txt)

**Comment by mattab** [comment]
Hi @entropywaves 
it should already work to import these log files in Piwik: did you try them? I think at least the w3c format should work

**Comment by entropywaves** [comment]
Bonjour Matthieu,

I've tried to import the W3C log but I see several error messages. I've tried the log format "icecast2" because it might be similar to shoutcast's standards (not completely sure) and "iis" (because IIs is W3C compliant?) to see if it imports. But both options won't work. I tried the following two commands to import:

python /usr/share/piwik/misc/log-analytics/import_logs.py --show-progress --url=http://192.168.1.25 --idsite=1 --recorders=8 --enable-http-errors --log-format-name=icecast2 --strip-query-string /opt/shoutcast/logs2/sc_w3c.txt

python /usr/share/piwik/misc/log-analytics/import_logs.py --show-progress --url=http://192.168.1.25 --idsite=1 --recorders=8 --enable-http-errors --log-format-name=iis --strip-query-string /opt/shoutcast/logs2/sc_w3c.txt

With both commands I see the following errors:

Fatal error: Piwik returned an invalid response: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>FNOOB TECHNO - Airtime</title>   <link href="/css/bootstrap.css?1be2b44a683235b6087d9d2784db2700" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/redmond/jquery-ui-1.8.8.custom.css?1be2b44a683235b6087d9d2784db2700" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/pro_dropdown_3.css?1be2b44a683235b6087d9d2784db2700" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/qtip/jquery.qtip.min.css?1be2b44a683235b6087d9d2784db2700" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/styles.css?1be2b44a683235b6087d9d2784db2700" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/masterpanel.css?1be2b44a683235b6087d9d2784db2700" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/tipsy/jquery.tipsy.css?1be2b44a683235b6087d9d2784db2700" media="screen" rel="styl

**Comment by entropywaves** [comment]
I see that in my previous comment the log results aren't displaying properly. Therefore I've attached the log txt file to the previous comment.

**Comment by mattab** [comment]
@entropywaves you need to specify `--url=http://192.168.1.25` that points to your Piwik server - is it the case?

**Comment by entropywaves** [comment]
Hi Matthieu,

Ok, I noticed I'm running Piwik on another port than the default port 80. I've adjusted the URL accordingly by adding the Piwik port number. Now it seems to communicate with the server. However I'm still unable to import the logfile properly. If I use log format icecast2 it doesn't import any lines (because it's probably the wrong format that isn't compliant with the Shoutcast format):

Logs import summary
-------------------

    0 requests imported successfully
    0 requests were downloads
    1588 requests ignored:
        1588 invalid log lines
        0 requests done by bots, search engines, ...
        0 HTTP errors
        0 HTTP redirects
        0 requests to static resources (css, js, ...)
        0 requests did not match any known site
        0 requests did not match any requested hostname

Website import summary
----------------------

    0 requests imported to 1 sites
        1 sites already existed
        0 sites were created:

    0 distinct hostnames did not match any existing site:

Performance summary
-------------------

    Total time: 0 seconds
    Requests imported per second: 0.0 requests per second

I've also tried log format IIS since IIS because it's w3c compliant but then I get error messages while parsing the log:

python /usr/share/piwik/misc/log-analytics/import_logs.py --show-progress --url=http://192.168.1.25:8080 --idsite=1 --recorders=8 --enable-http-errors --log-format-name=iis --strip-query-string /opt/shoutcast/logs2/sc_w3c.txt
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
Parsing log /opt/shoutcast/logs2/sc_w3c.txt...
Traceback (most recent call last):
  File "/usr/share/piwik/misc/log-analytics/import_logs.py", line 1693, in <module>
    main()
  File "/usr/share/piwik/misc/log-analytics/import_logs.py", line 1657, in main
    parser.parse(filename)
  File "/usr/share/piwik/misc/log-analytics/import_logs.py", line 1529, in parse
    match = format.match(line)
  File "/usr/share/piwik/misc/log-analytics/import_logs.py", line 180, in match
    self.matched = self.regex.match(line)
AttributeError: 'NoneType' object has no attribute 'match'

Is there a suitable Piwik log format to import this specific w3c logfile properly?

Don't know if the entire command string that I'm using is correct too?:

python /usr/share/piwik/misc/log-analytics/import_logs.py --show-progress --url=http://192.168.1.25:8080 --idsite=1 --recorders=8 --enable-http-errors --log-format-name=iis --strip-query-string /opt/shoutcast/logs2/sc_w3c.txt

**Comment by entropywaves** [comment]
I've also tried a minimal version of the command, but it seems unable to import the logfile properly:

 python /usr/share/piwik/misc/log-analytics/import_logs.py --show-progress --url=http://192.168.1.25:8080 --idsite=1 --recorders=8 --enable-http-errors /opt/shoutcast/logs2/sc_w3c.txt
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
Parsing log /opt/shoutcast/logs2/sc_w3c.txt...
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
Fatal error: cannot automatically determine the log format using the first 100000 lines of the log file. \Maybe try specifying the format with the --log-format-name command line argument.

**Comment by entropywaves** [comment]
@mattab have you got any suggestions to tackle the above issue? It seems that the log format is wrong for this type of file, I've tried several settings but all didn't work. Hope you can help me out with this one...

**Comment by mattab** [comment]
Hi @entropywaves unfortunately we don't have much time available to work on Log Analytics at this time. Maybe you know python, or know someone who knows python, who could help with this?

**Comment by entropywaves** [comment]
@mattab a developer has taken a look at it and managed to add a parser for Shoutcast to the import script code. I've attached the adjusted import script to this post. Is it possible that you incorporate this code into future Piwik releases? You already have an Icecast parser and now you could add Shoutcast import to that too;-) Would be very nice...

[import_logs.zip](https://github.com/piwik/piwik-log-analytics/files/120190/import_logs.zip)

**Comment by entropywaves** [comment]
Forgot to mention, it works like this now:
python ../import_logs.py --log-format-name=shoutcast --url=http://x.x.x.x:80 --idsite=1 ../sc_w3c.log

**Comment by sgiehl** [comment]
Hi @entropywaves 
Thanks for the update. I've imported your changes and will issue a new pull request for it, so it is easier to review the changes.

**Comment by entropywaves** [comment]
Thanks for adding this feature!
