### ISSUE TITLE
Apache (2.4.6) vhosts_combined do not track username "%u" - piwik (2.15.0)

### ISSUE THREAD

**Issue by jgrisa** [piwik/piwik-log-analytics#115]
Helo

I have configured my apache log on the standard way:
___________________________________________
LogFormat "%v %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
---------
when I try to import a log file, via import_logs.py , the username data is not collected (the rest of the data is collected OK).

Here is a log line, that does not import the username "%u" field:
------------------------------------------
www.test.com 172.27.6.246 - usertest [09/Dec/2015:12:11:52 +0100] "GET /test/getToken.php HTTP/1.1" 200 32 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"
-----------------------------------------
(IP, vhost, browser, O.S. data is collected OK, but field "usertest" is not collected)

Here is the command line that I execute:
------------------------------------------------
python /software/apache/www/estadisticas/misc/log-analytics/import_logs.py --url=http://estadisticas.des.test.com --enable-http-errors --enable-http-redirects  --add-sites-new-hosts apache-new-2015-12-09.log  --recorders=1 --show-progress-delay=15
--------------------------

Output:
----------------------------------------
Logs import summary
-------------------

    4 requests imported successfully
    0 requests were downloads
    0 requests ignored:
        0 HTTP errors
        0 HTTP redirects
        0 invalid log lines
        0 requests did not match any known site
        0 requests did not match any --hostname
        0 requests done by bots, search engines...
        0 requests to static resources (css, js, images, ico, ttf...)
        0 requests to file downloads did not match any --download-extensions

Website import summary
----------------------

    4 requests imported to 1 sites
        1 sites already existed
        0 sites were created:

 ....
-------------------------------

(Notice: I have imported microsoft IIS  extended logs with user data correctly) 

Thanks in advance !

**Comment by jgrisa** [comment]
I have also test to import this logs entry 
----------------------------------------
www.test.com 172.27.6.246 - usertest [09/Dec/2015:12:11:52 +0100] "GET /test/getToken.php HTTP/1.1" 200 32 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"
-------------------------------------

with the apache logs formats:

--log-format-name=common_complete
and
--log-format-name=common_vhost

But It doesn´t track the username (the same issue as above)

**Comment by mattab** [comment]
Thanks for the report @jgrisa we will take a look soon, hopefully before 2.16.0 stable release. cc @diosmosis

**Comment by jgrisa** [comment]
I have tried import_logs.py from mew 2.16.0 and now, works fine.
Thanks a lot
