### ISSUE TITLE
Device detection in log import

### ISSUE THREAD

**Issue by zdenekhrib** [piwik/piwik-log-analytics#121]
I am using PIWIK 2.15 with log import only and I see a lot of "unknow client devices". If I do:

SELECT DISTINCT custom_var_v2 FROM `piwik_log_visit` WHERE `config_browser_name` = 'UNK' AND `custom_var_k2` = 'Not-Bot' AND `custom_var_v2` IS NOT NULL order by custom_var_v2

I get a lot of user agent strings that could be decoded correctly using the "Device detection" screen in the Piwik administration GUI, eg: "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)"

Is the log import technique using the same Device Detection method as Image/JavaScript technique?

I am using this command to import logs:
python2.7 /www/piwik/misc/log-analytics/import_logs.py --debug --debug --config=/www/piwik/config/config.ini.php --url=http://piwik.domain.tld --idsite=1 --recorders=4 --enable-http-errors --enable-http-redirects --enable-static --enable-bots --enable-reverse-dns --output=$LOGFILE --log-format-regex="(?P<ip>\S+) - (?P<userid>\S+) \s?[(?P<date>._?) (?P<timezone>._?)] '\S+ (?P<path>._?) \S+' (?P<status>\S+) (?P<length>\S+) '(?P<referrer>._?)' '(?P<user_agent>.*?)' (?P<generation_time_micro>\S+) (?P<sessionid>\S+)" --regex-group-to-visit-cvar="sessionid=Session ID" --exclude-path=/xforms-server --exclude-path=/demo/xforms-server --exclude-path=/exist/xmlrpc --exclude-path=/exist-demo/xmlrpc $FILENAME

Could the problem be caused by the "Session ID" custom var import?

**Comment by mattab** [comment]
yes the log import technique uses the same detection as Piwik itself, more or less. 

Can you please post a short log file (eg. 2 lines) and the command used to reproduce the issue, and the steps you take to reproduce?

**Comment by mattab** [comment]
Please submit any un-detected User Agents to our open source project of device detections: https://github.com/piwik/device-detector
