### ISSUE TITLE
403: Forbidden

### ISSUE THREAD

**Issue by tderflinger** [piwik/piwik-log-analytics#123]
Hi!

I am running Piwik on Nginx, latest version on Ubuntu. I would like to import a log file using log-analytics, but I get 403 Forbidden. Tried with auth-token and id and password but nothing worked.

What I run:
python import_logs.py --url=http://192.168.178.20/piwik/ --idsite=1 --token-auth=71c2dd52a32e748ebd47a41ffa9dd908 /vagrant/access_log

Thanks for your help in advance!

**Comment by mattab** [comment]
please check your web server error log file, likely something is blocking the incoming requests?

**Comment by viba1** [comment]
I had same kind of problem, due to Referrer-Policy tag
Could you check it with https://securityheaders.com/
