### ISSUE TITLE
2.15.0: Error when connecting to Piwik: HTTP Error 400: Bad Request [2]

### ISSUE THREAD

**Issue by shellshocker** [piwik/piwik-log-analytics#124]
Sorry due to a GitHub bug I can't post here: https://github.com/piwik/piwik-log-analytics/issues/119

My answer @mattab:
Found the problem but forget to update the issue. My nginx configuration was the problem. You can define the default index with:
`index some_existing_site;`

My config was:
`index piwik.php;`

But the right way to do it is:
`index index.php;`

**Comment by mattab** [comment]
thanks for letting us know
