### ISSUE TITLE
Support for importing AWS ELB access logs analytics

### ISSUE THREAD

**Issue by guilhermp** [piwik/piwik-log-analytics#131]
Hi,
I've been trying to parse AWS Elastic Load Balancer logs but without success so far. Does anyone know of a working regex to do this, or can suggest me a good document Piwik's log-format-regex?

The log-format-regex I've been trying to use is as follows:
`--log-format-regex='.* ((?P<date>.*?) (?P<elb>.*?) (?P<ip>.*?) (?P<port>.*?) (?P<ip_r>.*?) (?P<port_r>.*?) (?P<proc_time>.*?) (?P<backend_proc_time>.*?) (?P<response_proc_time>.*?) (?P<status>.*?) (?P<backend_status>.*?)  (?P<rd_bytes>\S+) (?P<length>\S+) "(?P<user_agent>.*?)" (?P<ssl_cipher>\S+) (?P<ssl_protocol>\S+)).*' `

And here's a log sample I found on [AWS documentation](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html#access-log-file-format):

` 2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.000086 0.001048 0.001337 200 200 0 57 "GET https://www.example.com:443/ HTTP/1.1" "curl/7.38.0" DHE-RSA-AES128-SHA TLSv1.2`

I was able to parse the same logs on AWStats after converting timestamps with sed so that they look like:
` 2015-05-13 23:39:43 my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.000086 0.001048 0.001337 200 200 0 57 "GET https://www.example.com:443/ HTTP/1.1" "curl/7.38.0" DHE-RSA-AES128-SHA TLSv1.2`

AWStats Log Format:
`LogFormat="%time2 %elb %host %host_port %host_r %host_r_port %request_processing_time %backend_processing_time %response_processing_time %code %other %received_bytes %bytesd %methodurl %uaquot %extra1 %extra2"`

**Comment by mclite** [comment]
Did you ever get a resolution on this?

**Comment by guilhermp** [comment]
@mclite, nope... ended up sticking with AWStats 👎

**Comment by sgiehl** [comment]
would anyone send me a example log file with various entries. I'd maybe give it a try to implement the format...

**Comment by mclite** [comment]
https://aws.amazon.com/blogs/aws/access-logs-for-elastic-load-balancers/
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html
@sgiehl

**Comment by sgiehl** [comment]
thx @mclite, guess I can use that to create a new import format. Will try to implement it, as soon as I have some time for it.

**Comment by sgiehl** [comment]
@mclite would you mind checking if the linked PR works for you?

**Comment by twit-russell** [comment]
This was great to find as we needed to process ELB logs now.  @sgiehl I was able to merge the import_logs.py into our piwik distribution and so far they are importing/processing just like our nginx logs were. Is there anything specific I should look for?

**Comment by sgiehl** [comment]
If no errors occur and the data reported in your piwik seems to be valid (nothing missing,...), guess we could merge that one in master.

**Comment by mclite** [comment]
I got caught up in a new feature at work for while. I'll load the data today.

**Comment by mattab** [comment]
Hi @mclite @guilhermp - please confirm whether the patch in: https://github.com/piwik/piwik-log-analytics/issues/140 works for you and lets you import ELB access logs?
