### ISSUE TITLE
Piwik & self signed certificates : urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed. Add new --accept-invalid-ssl-certificate

### ISSUE THREAD

**Issue by Daryes** [piwik/piwik-log-analytics#138]
Hello,
This happens when using a self signed ssl certificate on a https hosted Piwik. 
It doesn't happen when falling back to http or downgrading python, something already referenced in #42 .
Of course, it's not possible to import any logs with this

> 2016-05-11 19:10:58,171: [INFO] Error when connecting to Piwik: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
> 2016-05-11 19:10:58,171: [INFO] Max number of attempts reached, server is unreachable!
> Traceback (most recent call last):
>   File "piwik/misc/log-analytics/import_logs.py", line 2338, in <module>
>     resolver = config.get_resolver()
>   File "piwik/misc/log-analytics/import_logs.py", line 972, in get_resolver
>     return StaticResolver(self.options.site_id)
>   File "piwik/misc/log-analytics/import_logs.py", line 1383, in **init**
>     'SitesManager.getSiteFromId', idSite=self.site_id
>   File "piwik/misc/log-analytics/import_logs.py", line 1366, in call_api
>     return cls._call_wrapper(cls._call_api, None, None, method, **kwargs)
>   File "piwik/misc/log-analytics/import_logs.py", line 1353, in _call_wrapper
>     raise Piwik.Error(message, code)
> __main__.Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

A bug I didn't experienced before upgrading the system and thus, doing the same with python jumping to v2.7.11. As expected, since Python had a change in v2.7.9+, making mandatory the certificate validation, which wasn't the case before. 
Redhat compiled some workarounds [on this page](https://access.redhat.com/articles/2039753), most of them working on a global level.

I've attached a dedicated workaround patch for the log-analytics I've done after searching around a lot, but I'm no python dev, it would be helpfull to add the whole mechanic for a --no-ssl-validity-check or similar parameter

[SSL-workaround.txt](https://github.com/piwik/piwik-log-analytics/files/260305/SSL-workaround.txt)

**Comment by llsnndlldkm** [comment]
Today I received the same error message when I installed a Comodo EV-SSL SGC certificate:

2016-05-19 20:00:07,463: [INFO] Error when connecting to Piwik: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
Traceback (most recent call last):
  File "/var/www/folder/htdocs/analytics/misc/log-analytics/import_logs.py", line 2336, in <module>
    config = Configuration()
  File "/var/www/folder/htdocs/analytics/misc/log-analytics/import_logs.py", line 885, in __init__
    self._parse_args(self._create_parser())
  File "/var/www/folder/htdocs/analytics/misc/log-analytics/import_logs.py", line 865, in _parse_args
    self.options.piwik_token_auth = self._get_token_auth()
  File "/var/www/folder/htdocs/analytics/misc/log-analytics/import_logs.py", line 904, in _get_token_auth
    _url=self.options.piwik_url,
  File "/var/www/folder/htdocs/analytics/misc/log-analytics/import_logs.py", line 1366, in call_api
    return cls._call_wrapper(cls._call_api, None, None, method, **kwargs)
  File "/var/www/folder/htdocs/analytics/misc/log-analytics/import_logs.py", line 1350, in _call_wrapper
    if errors == config.options.max_attempts:
NameError: global name 'config' is not defined

**Comment by mattab** [comment]
We need to add a new option `--accept-invalid-ssl-certificate` - Pull request welcome :+1:

**Comment by mattab** [comment]
Fixed in  #199
