### ISSUE TITLE
When processing large iis log on windows, Piwik returns 500 Error after ~70,000 records

### ISSUE THREAD

**Issue by ghotiphud** [piwik/piwik-log-analytics#145]
The recommendation to restart with the `--skip=77204` option continues to error.

Building a new file with the already imported records deleted also errors.

Starting import_logs.py with a different log file works successfully, but then errors around 70,000 records again.

**Comment by ghotiphud** [comment]
Seems to be related to one of `--enable-http-errors --enable-http-redirects --enable-static
--enable-bots` as it's working okay without those options

**Comment by sgiehl** [comment]
Do you see any errors in the error_log of the piwik instance?
Have you maybe tried to check if it works with each of that options without the others? Maybe we could find out which of the options causes the problem

**Comment by ghotiphud** [comment]
I believe my error_log would be `C:/Windows/temp/PHP70_errors`, but I'm not certain and that file is mostly empty with no new errors in the past 4 days.  

I can try enabling the options one at a time to see if the errors come back, but I haven't fully convinced myself I've solved it 100% yet, so I'm going to parse in a week or two of log files first to eliminate the possibility it's just a lucky fluke.

**Comment by ghotiphud** [comment]
Alright, so I did some further digging, and it came down to the log having a ton of actions by our service account, which shows up in `piwik_log_visit` as a single visit.  `visit_total_actions` was a SMALLINT.  Changed that to an INT and now it's working great.  Also explains why turning off some of those options allowed it to get much further, probably due mostly to the static file access.

**Comment by mattab** [comment]
As this issue (`visit_total_actions` being too small) will be fixed in Piwik 3, I'm closing this issue. See: https://github.com/piwik/piwik/issues/9565
