### ISSUE TITLE
Problem with permission on config.ini.php

### ISSUE THREAD

**Issue by augustoferronato** [piwik/piwik-log-analytics#149]
Hi,

I have a problem running the script, using the command:

> ./import_logs.py --url=http://piwikurl/piwik --idsite=2 --recorders=4 --enable-http-errors --enable-http-redirects --enable-static --enable-bots /var/log/httpd/access_log

I receive the error:
**Fatal error: the configuration file/config/config.ini.php could not be read. Please check permission. This file must be readable to get the authentication token**

I configured the apache to accepted connections on the file

 

> < Directory /var/www/html/piwik/config/config.ini.php >
>         Options Indexes FollowSymLinks
>         Require ip IP/SUBNET
>         < /Directory >

What is wrong?

Thanks

**Comment by mattab** [comment]
The file must be readable by the current user running the script, not the webserver 

Clarified slightly error message in https://github.com/piwik/piwik-log-analytics/commit/e015a5443083d12b5db33062028219837e26fe7e
