### ISSUE TITLE
IP addresses being truncated on import

### ISSUE THREAD

**Issue by msigley** [piwik/piwik-log-analytics#169]
It seems the IP addresses in the log files are being truncated when they are imported into Piwik
![2017-03-20_1417](https://cloud.githubusercontent.com/assets/4201801/24114882/10daa830-0d78-11e7-8d90-d236d1cd0440.png)

I am importing logs from IIS 8.5 with the following options:
--enable-http-errors --enable-http-redirects --enable-static --enable-bots --log-format-name=w3c_extended --w3c-time-taken-millisecs --recorders=3

Here is a sample header and first line of one of the imported logs (I anonymized the data for a good test case):
#Software: Microsoft Internet Information Services 8.5
#Version: 1.0
#Date: 2016-03-30 18:18:00
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2016-03-30 18:18:00 255.255.255.255 GET / - 80 - 255.255.255.255 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64;+rv:51.0)+Gecko/20100101+Firefox/51.0 - 500 0 0 87

**Comment by mattab** [comment]
It looks like you anonimised the data which causes IP addresses to be truncated (IP Anonymisation)

**Comment by msigley** [comment]
There is no entry for ip masking in my config.inc.php. Does piwik do this by default now?




Get Outlook for Android









On Tue, Mar 21, 2017 at 6:12 PM -0400, "Matthieu Aubry" <notifications@github.com> wrote:












It looks like you anonimised the data which causes IP addresses to be truncated (IP Anonymisation)

**Comment by mattab** [comment]
see http://piwik.org/docs/privacy/

**Comment by msigley** [comment]
Thanks
