### ISSUE TITLE
Timestamp of all log entries is set to now on import

### ISSUE THREAD

**Issue by dr-falsch** [piwik/piwik-log-analytics#171]
I tried to import old logfiles with the following command:

    ./import_logs.py --url=http://...de/piwik  --show-progress --idsite=1 --log-format-name=ncsa_extended --token-auth=... --debug ~/logs/archiv/2007/womex.com/*.gz

In the directory is a logfile for every day of 2007, but Piwik puts every line as it would happen just now.

I logged the parsed date in "date_to_piwik" and it appears as Piwik recognizes the date correct. I checked the regex in "import_logs.py" and they seem to work fine.

Maybe the problem is related to another problem. The importer says the following:

    In order for your logs to be processed by Piwik, you may need to run the following command:
     ./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='http://...de/piwik'

But I if I try the command, I get the following error:

     Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>/kunden/womex.com/www/tools/piwik/console</b> on line <b>17</b><br />
     <br />
     <b>Parse error</b>:  syntax error, unexpected T_STRING in <b>/kunden/womex.com/www/tools/piwik/console</b> on line <b>17</b><br />

Unfortunately, I don't see any strange characters in the "console" script.

**Comment by mattab** [comment]
> But I if I try the command, I get the following error:

This looks like it could be due that your PHP CLI is not running PHP 5.5

>  Timestamp of all log entries is set to now on import 

Please check your token_auth - I guess it's wrong or not set to a user with at least admin access
