### ISSUE TITLE
Log Analytics git repository does not contain any LICENSE information

### ISSUE THREAD

**Issue by fwolfst** [piwik/piwik-log-analytics#172]
I assume it is GPLv3+ like piwik. However it is stated nowhere. Usually you would put a LICENSE or COPYING file in the root of the repository (I can create a PR for that if wanted, but need to know about Copyright holders, too).

**Comment by sgiehl** [comment]
Yes. It's GPLv3+. Feel free to create a PR

**Comment by mattab** [comment]
fixed in https://github.com/piwik/piwik-log-analytics/issues/175
