### ISSUE TITLE
Unable to run tests on Ubuntu 14.04

### ISSUE THREAD

**Issue by fwolfst** [piwik/piwik-log-analytics#173]
I am not a specialist if it comes to python, ubuntu, virtualenv and all that.

Situation is that I have an Ubuntu 14.04 with python, python3, virtualenv, python3-nosetests and python3-nose2 installed.

As my installation defaults to python2, I tried to use `virtualenv` to temporarily default to python3:

    virtualenv -p /usr/bin/python3 --distribute temp-python3
    source temp-python3/bin/activate

As neither of the nostest packages ship with `nosetest` (they are called `nosetest3` and `nose2-3`), I modified `tests/run_tests.sh` to use up one of these. However, in both cases, test execution fails, e.g. with

```
  File "/usr/lib/python3/dist-packages/nose2/util.py", line 107, in object_from_name
    module = __import__('.'.join(parts_copy))
  File "/(CHANGED)/piwik-log-analytics/tests/tests.py", line 607
    assert hits[0]['date'] == datetime.datetime(2015, 05, 13, 23, 39, 43)
                                                       ^
SyntaxError: invalid token
```

If I change the "05" to "5", other Syntax errors come up. I assume that the tests should run fine with the correct setup. Can anybody hint me on how to get the tests go green on a Ubuntu 14.04 - preferably without any additional apt-repositories (`--user` installations are fine, but I dont want to clutter my setup).

**Comment by sgiehl** [comment]
python 3 is not supported.

**Comment by fwolfst** [comment]
Damnit, learn to read, Felix.
