### ISSUE TITLE
SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded

### ISSUE THREAD

**Issue by gpakosz** [piwik/piwik-log-analytics#189]
Hello,

When importing logs with `import_logs.py` on a Piwik instance upgraded `1.12.0` to `3.1.1` (yeah...), I'm getting the following error:
```
FastCGI sent in stderr: "PHP message: Error in Piwik (tracker): Error query: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction In query: INSERT INTO `piwik_option` (option_name, option_value, autoload)  VALUES (?, ?, ?)  ON DUPLICATE KEY UPDATE option_value = ? Parameters: array (   0 => 'report_to_invalidate_5_2017-09-27',   1 => '1',   2 => 0,   3 => '1', )" while reading response header from upstream
```

I'm passing `--recorders=2`, `--recorder-max-payload-size=150` options to `import_logs.py`.

The log file in question is `6170` lines long and has nothing special at first sight. Killing `import_logs.py` and importing that one log again works ok.

How can I further troubleshoot please?
Things I checked so far:
  - on the PHP-FPM side, `max_execution_timeout` and `request_terminate_timeout` are set to 0

**Comment by mattab** [comment]
see also https://github.com/piwik/piwik/issues/10125

**Comment by mattab** [comment]
@gpakosz please add your comment/thoughts on the issue: https://github.com/piwik/piwik/issues/10125

will close this one as duplicate
