### ISSUE TITLE
Log analytics - UTF-8 link from search bug

### ISSUE THREAD

**Issue by soulcreate** [piwik/piwik-log-analytics#33]
I use piwik/misc/log-analytics/import_logs.py for my log analytics.
A small part of queries is defined as ????. However, if you look at the source HTML, then everything is OK. 
 In the picture on the link address http://yandex.ru/yandsearch?text=%EA%F3%EF%E8%F2%FC+%E2%FB%EF%F3%F1%EA%ED%EE%E5+%EF%EB%E0%F2%FC%E5&lr=213 
 which was well converted into Russian. 
 It is observed on 20% of all requests from Russian yandex and google.
![piwik log analytics](https://cloud.githubusercontent.com/assets/2090261/3711572/0ec303d0-14dd-11e4-9d2f-24e2572e9134.png)

Migrated from piwik/piwik#5885

**Comment by mattab** [comment]
I think this issue is not related to log analytics.  Please open new issue with steps to reproduce in github.com/piwik/piwik/issues
