### ISSUE TITLE
Map URL Query string parameter to Custom Variables

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-log-analytics#44]
The goal of this issue is to let users define a set of URL Query string Parameters that they want to store as Custom Variables of scope `page` in the request. 

For example imagine in the log file we have a URL path such as `/page?pageTitle=Hello, world&pageId=com.x.y.us.abc&countryCode=us&accountCode=us1234&accountName=Testaccount`

User may want to configure:
 * URL parameter `pageId`, record it in Custom Variable slot 5 with name = `pageId`, value = `com.x.y.us.abc`
 * URL parameter `countryCode`, record it in Custom Variable slot 6, name = `countryCode`, value = `us`
 * URL parameter `accountName`, record it in Custom Variable slot 7, name = `accountCode`, value = `Testaccount `
 * etc.

Possible solution:
 * This could be done for example with a new parameter to the `import_logs.py` script:
  * `--query-string-parameters-to-custom-variables="pageId:5,countryCode:6,accountName:7"`
 * I'm not sure whether this functionnality should be done in the `import_logs.py`  or maybe it should instead be done as a new custom plugin 
  * in this way it lets any website reuse this Query string -> Custom vars mapping.

Migrated from piwik/piwik#6812

**Comment by mattab** [comment]
This will not be done in Log Analytics but instead we will implement a more generic solution involving: Custom Dimensions https://github.com/piwik/piwik/issues/9129 and then "Extracting URL query parameter into a Custom Dimension". This will be beautiful!

**Comment by mattab** [comment]
This can be done with our new plugin http://plugins.piwik.org/CustomDimensions

**Comment by jloh** [comment]
This never appeared to make it into the plugin I don't think? I can't seem to extract the query param like you say.

**Comment by mattab** [comment]
@jloh it should be possible: you can now create Custom Dimensions of Action scope. In the custom dimension definition you can define regular expression and extract the custom dimension value from URL query parameters using regular expression or not. Could you try this?

**Comment by jloh** [comment]
@mattab this does work (I think I just tested it right...) but it means that the page URL in the Pages report now has a random query string on it which I'd prefer not to have.

Any way around this?

**Comment by mattab** [comment]
@jloh can you try to exclude URL parameters in Piwik (see: https://piwik.org/faq/how-to/faq_81/ ) and then, does the Custom Dimension still work? (I'm not sure whether Custom Dimension plugin reads the URL values before or after the URL query exclusion)
