### ISSUE TITLE
import_logs.py does not work in apache 2.4 in pipe mode

### ISSUE THREAD

**Issue by karlsoon** [piwik/piwik-log-analytics#46]
Hi!
Script does not record lines.
This is example of output:
212 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
No any errors in log with -d.
How i can help you to find the problem?
I tried 2.9.1 and master version.

Migrated from piwik/piwik#6805

**Comment by nuxwin** [comment]
I cannot confirm this ;) All is working as it should.

Tested on Debian Jessie:

```
root@jessie:/var/www/virtual/test.tld/piwik/htdocs/misc/log-analytics# apache2ctl -v
Server version: Apache/2.4.10 (Debian)
Server built:   Aug 28 2015 16:28:08
```

Logs are imported correctly. All is about configuration there ;)

My piped log Apache2 conf:

```
LogFormat "%v %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" piwikLogFormat
CustomLog "||/var/www/virtual/test.tld/piwik/htdocs/misc/log-analytics/import_logs.py \
--debug --debug --debug --enable-http-errors --enable-http-redirects --enable-bots --enable-http-redirects \
--url=http://piwik.test.tld --output=/var/log/piwik.log --recorders=1 \
--recorder-max-payload-size=1 --log-format-name=common_complete \
-" piwikLogFormat
```

Tested with import_logs.py from stable release: 2.14.3

**Comment by mattab** [comment]
Thanks @nuxwin for your feedback & notes!

> My piped log Apache2 conf (for testing purpose):


Maybe we could include it in the README if maybe the readme is not clear about this...

**Comment by falstaff84** [comment]
Just hit that today. I think what is mainly missing in the README is that the format should be switched to common_complete.

**Comment by mattab** [comment]
Hi  @falstaff84  - any chance you could submit a pull request for the README to add this information? it would be really helpful :+1:

**Comment by tillsteinbach** [comment]
I also cannot get it working with Apache 2.4

My output in the log always ends with:
2016-06-03 14:05:23,776: [DEBUG] Resolver: static
2016-06-03 14:05:23,931: [DEBUG] Launched recorder

instead of
Parsing log (stdin)...

when the script is launched from apache and not from the command line

Any help is highly appreciated!

**Comment by mattab** [comment]
Thanks @nuxwin for your note. README was improved in https://github.com/piwik/piwik-log-analytics/commit/f9f780c8f7aec63582b92e5e8660f517357b5cee
