### ISSUE TITLE
 Add retry mechanism to import_logs.py 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-log-analytics#60]
Request from Tomasz from Admin team:

At this moment on any timeout from frontend server (which happens from time to time) script breaks.
Not sure who should do it, but we need some kind of retry mechanism to import_logs.py script.

@diosmosis what would you suggest?

**Comment by diosmosis** [comment]
I don't know of an easy way to implement this since the log importer uses BulkTracking. We'd have to be able to import visits while recognizing if a visit has already been tracked, otherwise visits can be tracked more than once. If inaccuracies aren't an issue, then we can either allow retrying the request (which may already be done by the script) or just ignore the failure and continue.

**Comment by mattab** [comment]
There is in the code somewhere a SQL transaction wrapped around (I think around the bulk request.)

Maybe we could ensure that whenever a visit fails to insert within the transaction then the whole Bulk tracking request fails (maybe it already works in this way). Then it would be safe to retry... would it work?

**Comment by diosmosis** [comment]
Should work, we could probably add a system test for it.

Btw, I looked in the code and it should already retry using the PIWIK_MAX_ATTEMPTS constant. Maybe we can make the configurable? And if the max is exceeded, log to the screen and continue?

**Comment by mattab** [comment]
Good to know that we already retry, here are suggestions:

 * increase the sleep timeout to 10s, (2s was too low)
 * increase PIWIK_MAX_ATTEMPTS to 10
  * by default we would give the server 100s=1min40s to come back to life - hopefully it's enough for most temporary errors
 * let's improve if applicable logging to screen to let admin clearly see that we re-tried and failed N times
 * +1 to test that the retry really works when  server cannot be reached or times out
