### ISSUE TITLE
Do not parse logs via regex

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik-log-analytics#61]
I've noticed in order to fully support the W3C format, regexes have to get more and more complicated. But, the log format is pretty simple, every field is separated by one or more spaces and can be a string w/ no space characters, or a quoted string. We shouldn't need a super complicated regex to parse these logs.

Additionally, other normal log formats (ie, common, ncsa extended, etc.) look as though they can be parsed in the same way as W3C format w/o having to have separate specific regexes.

**Comment by mattab** [comment]
Seems we're stuck with regex for now
