### ISSUE TITLE
custom regex works outside of Piwik but not passed into log_import.py

### ISSUE THREAD

**Issue by fogelfish** [piwik/piwik-log-analytics#66]
This was a hitch I encountered while trying to import custom parameters contained in apache logs.  I wanted to do it by passing custom regex on the command line into import_logs.py.  For the record I ended up defining my custom regex inside import_logs.py and I edited the script to capture those custom parameters.  For a description of what I did see https://github.com/piwik/piwik-log-analytics/issues/20

I had regex that found a match outside of Piwik.  But it did not return a match when I passed it into the import_logs.py script.

Here's a line from the apache log:

```
92.224.96.192 - - [24/May/2014:23:59:51 -0700] "GET /path/to/resource/image.GIF HTTP/1.1" 200 6652 "http://subdomain.obscured.com/path/to/resource/" "Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.17" i=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9; t=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9
```

The custom regex was:

```
(?P<host>[\w\-\.]*)(?::\d+)?[\s-]+\[(?P<date>.*?)[\s-]+(?P<timezone>.*?)\][\s]+"(?P<request>.*?)[\s]+(?P<path>.*?)[\s]+(?P<protocol>[\w\/\.]*)"[\s]+(?P<status>[\d]*)[\s]+(?P<bytes>[\d|-]*)[\s]+"(?P<url>.*?)"[\s]+"(?P<user_agent>.*?)"[\s]+(?:.*)i=(?:[\w]*)(?::[\w]*);[\s]+(?:.*t=(?!.*t=)(?P<sessionid>[\w]*))
```

I'm not sure what went wrong... probably had to do with encoding/decoding. My log was ASCII (ISO-8859-1). The python script changed it to unicode. At the point in import_logs.py where the match is tried...

``` python
match = format.match(line)
```

…here is the same line:

```
u'92.224.96.192 - - [24/May/2014:23:59:51 -0700] "GET /books/howmany/firefightingaddition/3small.GIF HTTP/1.1" 200 6652 "http://subdomain.obscured.com/path/to/resource/" "Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.17" i=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9; t=sarameitner85310:707cddd7a0bfdaa42b89597ac76c9ba9
```

I'm not using Piwik at this time, but in case this is useful to others, I wonder which <code>--encoding</code> flag should I have used to prevent this translation? Or was this due to the regex itself?  Or is this a bug?

**Comment by mattab** [comment]
Hi @fogelfish 
Thanks for the report. It may be a bug.

If you experience this bug again and have more information, or if anyone else experiences this, please leave a comment
