### ISSUE TITLE
Support when Piwik is behind HTTP Auth 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-log-analytics#70]
The goal of this issue is to let user import logs even when Piwik server is protected by HTTP Auth. 

For example we could add `-http-user` and `--http-password` parameters to let user specify HTTP username and password. 

this feature was requested several times and more recently in [this forum post](http://forum.piwik.org/read.php?2,126284)

**Comment by Framartin** [comment]
@mattab  I think this issue should be closed because this was fix in d1662c2cdfee56379ad871fd880db4caae0f6ad4

**Comment by mattab** [comment]
Thanks for the tip!
