### ISSUE TITLE
No filename/lineno on error 400

### ISSUE THREAD

**Issue by cbay** [piwik/piwik-log-analytics#72]
I've recently upgraded Piwik, and now when piwik_import_logs gets an error 400 during the import, it doesn't give the filename/fileno. I'm pretty sure it was specified in previous versions.

**Comment by mattab** [comment]
Do you maybe have an example of what filename/fileno you would like to see when there is a 400 error?

**Comment by cbay** [comment]
I think it's hard to pinpoint the exact filename/lineno that failed, but I think we should at least print the number of parsed lines in fatal_error if no filename/fileno was passed. This way you'd have a rough estimate of where it failed, which is better than no estimate at all.
