### ISSUE TITLE
Error 400 when receiving an unexpected website

### ISSUE THREAD

**Issue by cbay** [piwik/piwik-log-analytics#73]
I got an error 400:
Error in Piwik (tracker): An unexpected website was found, check idSite in the request

This should not be a fatal error in my opinion, as it can happen in sane situations. The typical use case is a website which got deleted during the import, which is far from being unusual when your import takes a long time (and you are not your only user).

I use the dynamic resolver, which caches the websites IDs. I think we should just ignore unexpected websites, or at least have an option to ignore them if it's not considered a normal use case. Maybe even better, let Piwik return warnings which whould be printed at the end of the import process.

**Comment by mattab** [comment]
> Maybe even better, let Piwik return warnings which whould be printed at the end of the import process.

It sounds good. Maybe we ignore the 400 errors during import and then print a summary at the end of all 400 errors something like: `Warning: 1500 requests returned error 400: An unexpected website was found, check idSite in the request` or similar.
