### ISSUE TITLE
 NameError: global name 'config' is not defined 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-log-analytics#74]
This error is now displayed to users in some cases, as reported in forum, with possible patch: http://forum.piwik.org/read.php?2,126436

**Comment by zAfLu** [comment]
Have the same issue with the current stable AND nightly build

**Comment by mattab** [comment]
Hi @diosmosis could you investigate this one after your current work?

**Comment by mattab** [comment]
Hi @diosmosis could you investigate this one after your current work?
