### ISSUE TITLE
Piwik upgrade to latest version failed

### ISSUE THREAD

**Issue by bsmurali** [piwik/piwik-log-analytics#76]
When I tried to launch the piwik on the browser with the following URL

http://localhost/piwik/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday

I get the following error page.

( ! ) Fatal error: Call to undefined method Piwik\Menu\MenuTop::addEntry() in C:\wamp\www\piwik\plugins\ExampleUI\ExampleUI.php on line 48
Call Stack
#	Time	Memory	Function	Location
1	0.0008	253944	{main}( )	..\index.php:0
2	0.0158	1286800	require_once( 'C:\wamp\www\piwik\core\dispatch.php' )	..\index.php:27
3	0.9089	13623424	Piwik\FrontController->dispatch( )	..\dispatch.php:31
4	0.9095	13629880	Piwik\FrontController->doDispatch( )	..\FrontController.php:97
5	0.9386	15212544	call_user_func_array ( )	..\FrontController.php:531
6	0.9386	15212704	Piwik\Plugins\CoreHome\Controller->index( )	..\FrontController.php:531
7	0.9389	15213152	Piwik\Plugins\CoreHome\Controller->getDefaultIndexView( )	..\Controller.php:170
8	1.0004	16331400	Piwik\Plugin\Controller->setGeneralVariablesView( )	..\Controller.php:132
9	1.0209	16787224	Piwik\Menu\MenuTop->getMenu( )	..\Controller.php:639
10	1.0209	16787536	Piwik\Piwik::postEvent( )	..\MenuTop.php:70
11	1.0209	16787632	Piwik\EventDispatcher->postEvent( )	..\Piwik.php:699
12	1.0212	16788912	call_user_func_array ( )	..\EventDispatcher.php:130
13	1.0212	16789072	Piwik\Plugins\ExampleUI\ExampleUI->addTopMenuItems( )	..\EventDispatcher.php:130
A fatal error occurred

Please contact the system administrator, or login to Piwik to learn more.

**Comment by mattab** [comment]
Hi @bsmurali 

Can you please delete the file: `piwik\plugins\ExampleUI\ExampleUI.php`

This will fix the issue. (We will investigate further this issue in #7986)
