### ISSUE TITLE
import_logs.py should look for https host if no http host is found

### ISSUE THREAD

**Issue by rhurling** [piwik/piwik-log-analytics#77]
Hi,

I currently have the problem that I want to auto-import my log files which didn't work, because the import_logs.py `DynamicResolver` class only looks for 'http://' + host in Piwik, but all my Sites are https only and created in piwik accordingly.

The following change to the `_get_site_id_from_hit_host` function would allow the script to look for a https host if no http host is found.

```python
    def _get_site_id_from_hit_host(self, hit):
        main_url = 'http://' + hit.host
        res = piwik.call_api(
            'SitesManager.getSitesIdFromSiteUrl',
            url=main_url,
        )
        if res:
            return res

        main_url = 'https://' + hit.host
        return piwik.call_api(
            'SitesManager.getSitesIdFromSiteUrl',
            url=main_url,
        )
```

**Comment by mattab** [comment]
Hi @rhurling,
Thanks for the report, good find

**Comment by mattab** [comment]
Note that to have this issue actually fixed we will need this Pull request merged: https://github.com/piwik/piwik/issues/8070

it will be done in the next Piwik 2.14.0 beta version available next week
