### ISSUE TITLE
--add-sites-new-hosts add sites multiple times

### ISSUE THREAD

**Issue by chrodriguez** [piwik/piwik-log-analytics#80]
When using json format and run script with `--add-sites-new-hosts` option, each time the script is run, new sites are created. 

Looking inside the code, it seems that when `_get_site_id_from_hit_host` is called an API call to `SitesManager.getSitesIdFromSiteUrl` is done without prefixing with *protocol*

I fixed it in my branch, so I will create a PR with the fix

**Comment by halfdan** [comment]
What does your log look like? I think most log formats contain the protocol (which makes the lookup work). You may want to change that PR to only prefix `http://` if `hit.host` doesn't already contain the protocol.

**Comment by chrodriguez** [comment]
I followed the README where it explains how to configure nginx to log json directly. The *host* parameter, from nginx documentation is defined as:

```
$host
in this order of precedence: host name from the request line, or host name from the “Host” request header field, or the server name matching a request
```

A line from my nginx json log format looks like:

```json
{
  "ip": "66.249.64.157", 
  "host": "www.extensionistas.unlp.edu.ar", 
  "path": "/article/printPreview/id/111", 
  "status": "200", 
  "referrer": "-", 
  "user_agent": "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)", 
  "length": 2730, 
  "generation_time_milli": 0.043, 
  "date": "2015-06-29T03:08:13-03:00"
}
```  

When I wrote the patch, I though it would be usefull to check if protocol is setted, but as variable was named host, I assumed it doesn't contains protocol. 

I will change it and update my PR

**Comment by halfdan** [comment]
@chrodriguez You might be right - the protocol is added just a few lines later: https://github.com/chrodriguez/piwik-log-analytics/blob/a2316b97473227bff31ec62611f488c74763fdda/import_logs.py#L1323

**Comment by chrodriguez** [comment]
@halfdan I've just create a new PR. I think this one solves the problem

**Comment by chrodriguez** [comment]
I've tested it and it's working. Do you think this patch can be merged?

**Comment by mattab** [comment]
It's working in 2.14.0 - issue is that you used latest version of log analytics with older Piwik (usually this works, but not here). we do not support running newer log analytics with older piwik (often it works but we don't support it)
