### ISSUE TITLE
ip and date are not sent to piwik

### ISSUE THREAD

**Issue by goyome** [piwik/piwik-log-analytics#82]
I have the same problem as Matthias described in this post : 
http://forum.piwik.org/read.php?2,128257

Everything I import gets recorded with the date and the ip of the server the import is running.

To reproduce it, try to import the following lines : 
 ```
104.245.98.66 - - [16/Jul/2015:20:39:58 +0200] "GET /public/test.pdf HTTP/1.1" 200 1525912 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; TencentTraveler ; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; .NET CLR 2.0.50727)"
105.100.3.146 - - [16/Jul/2015:13:33:39 +0200] "GET /public/UPV-M/Test2.pdf HTTP/1.1" 200 23346990 "https://www.google.dz/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"
105.101.4.47 - - [16/Jul/2015:01:37:38 +0200] "GET /public/test.pdf HTTP/1.1" 200 22456933 "http://www.google.fr/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"
```

The regex seems correct. When using --dump-log-regex, I got this : 
```
[INFO] Using format 'ncsa_extended'.
[INFO]Regex being used: (?P<ip>\S+)\s+\S+\s+\S+\s+\[(?P<date>.*?)\s+(?P<timezone>.*?)\]\s+"\S+\s+(?P<path>.*?)\s+\S+"\s+(?P<status>\S+)\s+(?P<length>\S+)\s+"(?P<referrer>.*?)"\s+"(?P<user_agent>.*?)"
```

Piwik 2.14.1
Php 5.3

**Comment by goyome** [comment]
To complete the tests, I tried on a newer php box (php 5.6), and I faced the same behaviour.
The problem doesn't seem to be linked to an old version of php.

**Comment by alessandrocanovi** [comment]
I am experiencing the same issue using 2.14.3
On 2.13.1 everything was fine

**Comment by diosmosis** [comment]
Hi @goyome or @alessandrocanovi, can you set the `[Tracker] debug=1` INI config, add `logging.debug(response)` before this line in import_logs.py: https://github.com/piwik/piwik-log-analytics/blob/master/import_logs.py#L1180, run the log importer with a log file that contains ONE log line (using the --debug parameter), then send the output to hello@piwik.org?

Can you also list if you are using any plugins from the marketplace or custom plugins?

If you are using LoginLdap, I suspect the issue at play here is this one: https://github.com/piwik/piwik/issues/8509. If this is the problem, this change to LoginLdap will fix it: https://github.com/piwik/plugin-LoginLdap/commit/360671c46893410223264e32a1d5de4feb62f3eb

**Comment by goyome** [comment]
Hi @diosmosis, you just find the origin of the problem.
We are using the LoginLdap plugin and the fix you suggested solved the issue.
So upgrading LoginLdap to 3.1.5 should solve this issue.

Thanks a lot for the time spent on this.

**Comment by alessandrocanovi** [comment]
Hi @diosmosis, problem solved also for me upgrading LoginLdap.
Many thanks
