### ISSUE TITLE
wrong statistics after update 2.14

### ISSUE THREAD

**Issue by Arnoade** [piwik/piwik-log-analytics#84]
Hello,

Here, you can find a description of the problem : http://forum.piwik.org/read.php?2,128230
So, i import log file with the same python script version on Piwik 2.13 and on Piwik 2.14
I create a new site on Piwik 2.13 & 2.14 only for the test.
(Piwik 2.13 used a new db only for the test.)
As you can see on screenshots, the result is completly different according to piwik version.
I test with others scripts version, no change.

The log file i use for test (200 lines) is an apache ncsa extended log format.
I 've the same problem with w3c log format.
 
The Log output is the same for 2.13 or 2.14 : 

Logs import summary
-------------------

    107 requests imported successfully
    62 requests were downloads
    93 requests ignored:
        10 HTTP errors
        0 HTTP redirects
        0 invalid log lines
        0 requests did not match any known site
        0 requests did not match any --hostname
        75 requests done by bots, search engines...
        8 requests to static resources (css, js, images, ico, ttf...)
        0 requests to file downloads did not match any --download-extensions

Website import summary
----------------------

    107 requests imported to 1 sites
        1 sites already existed
        0 sites were created:

    0 distinct hostnames did not match any existing site:

Have you got an idea ? 
If necessary, i can send the logfile.

Thank you in advance for your help.

Have a nice day

Arno

Piwik 2:13 result : 

![piwik2 13](https://cloud.githubusercontent.com/assets/13452016/8826116/572e58c2-3084-11e5-99ee-81e209888d7c.png)

Piwik 2.14 result :

![piwik2 14](https://cloud.githubusercontent.com/assets/13452016/8826120/5bb46788-3084-11e5-9a57-5016eb4e6463.png)

**Comment by mattab** [comment]
Hi @Arnoade 
One of your Piwik has IP Anonimisation enabled. please make sure your setting are the same on both piwik

**Comment by Arnoade** [comment]
Hello, 
i set same settings both sides now, but no changes after parsing log file...
Arno

**Comment by alessandrocanovi** [comment]
I am experiencing the same issue, it seems that the visitor IP of imported logs is always the Piwik server IP.
IP anonymization is disabled.
I've opened a new issue since this one has been closed https://github.com/piwik/piwik/issues/8486
