### ISSUE TITLE
download files/browser recognition problem

### ISSUE THREAD

**Issue by mucctecc** [piwik/piwik-log-analytics#85]
I am using the logFile data attached below (test.txt).

When calling

python /var/www/piwik/misc/log-analytics/import_logs.py --url=https://xxx.yyy.zzz.de test.txt --idsite=39 --recorders=4 --enable-http-errors --enable-http-redirects --log-format-name=common

the download files are correctly recognized but there is no information about the browser type of the visitors.

When calling instead

python /var/www/piwik/misc/log-analytics/import_logs.py --url=https://xxx.yyy.zzz.de test.txt --idsite=38 --log-format-regex='(?P<ip>._)\s-\s[a-zA-Z0-9-]._[(?P<date>._?) (?P<timezone>._?)] \"(?P<path>._?)\"\s(?P<status>\S+) (?P<length>\S+)\s\"(?P<user_agent>._?)\"\s\"(?P<referrer>.*?)\"' --recorders=4 --enable-http-errors --enable-http-redirects

it is just the other way round. There is information in Piwik about the browsers but none about the download files. 

___________(test.txt)___________________________________
11.111.111.111 - dObUR1SqaQnIIGx [05/Aug/2015:00:00:00 +0100] "GET https://examenonline.thieme.de:443/eonline/frage/3088 HTTP/1.1" 200 7324 "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0" "https://examenonline-thieme-de.emedien.xx.yyy.de/eonline/sitzung/7344304/frage/2102"
22.222.22.22 - IfgBjHWNHyk256H [05/Aug/2015:00:00:00 +0100] "GET http://www.bdsl-online.de:80/BDSL/stylesheets/BDSL.css HTTP/1.1" 304 0 "Mozilla/5.0 (Windows NT 6.1; rv:39.0) Gecko/20100101 Firefox/39.0" "http://www.bdsl-online.de.emedien.xx.yyy.de/BDSL-DB/suche/ergebnismenge.xml?step=16&vid=B94EB2B0-EF04-47F3-8886-D4799D3C9CE6&Skript=ergebnis&SucheNr=1&Suchtyp=1&contenttype=text/html"
33.333.33.33 - IfgBjHWNHyk256H [05/Aug/2015:00:00:00 +0100] "GET http://www.bdsl-online.de:80/BDSL/javascript/functions.js HTTP/1.1" 304 0 "Mozilla/5.0 (Windows NT 6.1; rv:39.0) Gecko/20100101 Firefox/39.0" "http://www.bdsl-online.de.emedien.xx.yyy.de/BDSL-DB/suche/ergebnismenge.xml?step=16&vid=B94EB2B0-EF04-47F3-8886-D4799D3C9CE6&Skript=ergebnis&SucheNr=1&Suchtyp=1&contenttype=text/html"
44.444.44.44 - IfgBjHWNHyk256H [05/Aug/2015:00:00:00 +0100] "GET http://www.bdsl-online.de:80/BDSL/image/box/spacer.gif HTTP/1.1" 304 0 "Mozilla/5.0 (Windows NT 6.1; rv:39.0) Gecko/20100101 Firefox/39.0" "http://www.bdsl-online.de.emedien.xx.yyy.de/BDSL-DB/suche/ergebnismenge.xml?step=16&vid=B94EB2B0-EF04-47F3-8886-D4799D3C9CE6&Skript=ergebnis&SucheNr=1&Suchtyp=1&contenttype=text/html"
555.55.5.555 - 55MBLfnetsRAXxn [05/Aug/2015:00:00:00 +0100] "GET https://www.thieme-connect.de:443/products/ebooks/pdf/10.1055/b-0034-93627.pdf HTTP/1.1" 200 622725 "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0" "https://www-thieme-connect-de.emedien.xx.yyy.de/products/ebooks/book/10.1055/b-002-94102"

**Comment by mattab** [comment]
Hi there,

I don't know if this is a bug, maybe it is an issue with your custom regex?
