### ISSUE TITLE
--idsite option seems to be ignored when used with --reply-tracking

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-log-analytics#97]
It looks like it's set initially here https://github.com/piwik/piwik-log-analytics/blob/master/import_logs.py#L1591
and then overwritten here https://github.com/piwik/piwik-log-analytics/blob/master/import_logs.py#L1600

Example command:

```
/home/vagrant/www/piwik/misc/log-analytics/import_logs.py --url=http://apache.piwik/ --replay-tracking '/home/vagrant/www/testfiles/ecommerce_idsite_5.log' --idsite=5 2>&1
```

To test it one can use eg the ecommerce log file from Piwik repository: `plugins/VisitorGenerator/data/ecommerce.log`

It's weird as I thought I tested it initially and worked but now realize that it doesn't work. Also I'm not 100% if it's a bug or feature but does sound like a bug to me. Would need this feature for a custom plugin.

**Comment by mattab** [comment]
> It's weird as I thought I tested it initially and worked but now realize that it doesn't work. Also I'm not 100% if it's a bug or feature but does sound like a bug to me. 

:+1: if `--idsite` is set, then it should be applied at all times (it's a useful feature too)

**Comment by tsteur** [comment]
@diosmosis do you mind having a look at https://github.com/piwik/piwik-log-analytics/pull/99 ?
